apiVersion: v1
kind: Pod
metadata:
  name: jdbcdriver
  labels:
    app: jdbcdriver
spec:
  volumes:
    - name: drivers-pv-storage
      persistentVolumeClaim:
        claimName: drivers-pvc
    # - name: jdbc-config-map
    #   configMap:
    #     name: jdbc-driver-configmap
    #     defaultMode: 0777
  containers:
  - name: jdbcdriver
    image: alpine
    command: ['sh', '-c', 'echo The app is running! && cd jdbc_driver && wget https://download.microsoft.com/download/f/c/d/fcd3f599-2d60-46c1-8628-45c2eff1b207/sqljdbc_8.4.1.0_enu.tar.gz && sleep 3600']
    # command: ['sh', '-c', 'echo The app is running! && cd jdbc_driver/scripts && ./getJdbcDriver.sh && sleep 3600']
    volumeMounts:
        - name: drivers-pv-storage
          mountPath: "/jdbc_driver"
        # - name: jdbc-config-map
        #   mountPath: "/jdbc_driver/scripts"
      
  # initContainers:
  # - name: init-myservice
  #   image: busybox:1.28
  #   command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
  # - name: init-mydb
  #   image: busybox:1.28
  #   command: ['sh', '-c', "until nslookup mydb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"]
